# Generated by Django 5.0.3 on 2024-03-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('age', models.IntegerField(verbose_name='age')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('category', models.CharField(choices=[('dogs', 'dogs'), ('cats', 'cats')], max_length=120)),
                ('image', models.ImageField(default='default.png', upload_to='Adopt_images')),
            ],
            options={
                'verbose_name_plural': 'Adopt',
                'db_table': 'pets',
            },
        ),
    ]
