# Generated by Django 5.0.3 on 2024-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptpet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
