# Generated by Django 5.0.3 on 2024-03-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptpet', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'CartItem'},
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart items',
        ),
    ]
